### ISSUE TITLE
Run d2d analysis on many projects

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/scancode.io#1437]
For each, we should define a set of interesting projects then analyze, and then review results for accuracy:

- [ ] Run pipeline for 100 Windows C++ projects
- [ ] Run pipeline for 100 macOS projects
- [ ] Run pipeline for 100 .Net projects
- [ ] Run pipeline for Java and native code and Android apk and dex classes
- [ ] Run pipeline for Python and C/C++ source and the python bytecode and native binaries
- [ ] Run pipeline for Rust source and binaries
- [ ] Run pipeline for Ruby source and gem packages
- [ ] Run pipeline for JavaScript

**Comment by tdruez** [comment]
# Progress update [on Jan 17 2024]

## Reports available for:

- [100 Windows C++ projects](https://github.com/aboutcode-org/scancode.io/issues/1470#issuecomment-2598067546)
- [100 macOS projects](https://github.com/aboutcode-org/scancode.io/issues/1471#issuecomment-2598037252)
- [100 .Net projects](https://github.com/aboutcode-org/scancode.io/issues/1472#issuecomment-2598016794)
- [Java and native code and Android apk](https://github.com/aboutcode-org/scancode.io/issues/1473#issuecomment-2598006424)
- [Ruby source and gem packages](https://github.com/aboutcode-org/scancode.io/issues/1476#issuecomment-2588254889)

## TODO: We still need a projects listing for the following:
- #1474
- #1475
- #1477

**Comment by pombredanne** [comment]
> ## Next: "Collect and review issues and accuracy"
> 
> @pombredanne How do you want to proceed for the "review" part?

@tdruez @AyanSinhaMahapatra  the review consist in:
1. looking at all discrepancies with a TODO/REVIEW status
2. Fix most problems, or enter issues for larger more complex problems
3. Collect a clean set of issues and determine if these are things we could report upstream as problems
3.1. ideally, we would want to determine unknown bundled packages and check for unknown vulnerabilities or license issues from these inclusions

**Comment by AyanSinhaMahapatra** [comment]
@tdruez I've done a initial review of Rust, Ruby and ELF pipeline runs:

We need to rerun these after the following PRs are merged as these add ruby/elf specific functionality and also some stats functionality for debugging:

* https://github.com/aboutcode-org/scancode.io/pull/1621 (elfs + rust)
* https://github.com/aboutcode-org/scancode.io/pull/1550 (ruby)

I've also reported an issue based on the initial review with @pombredanne, see https://github.com/aboutcode-org/source-inspector/issues/28 which is required to improve matching accuracy with symbols. This is also related to rust/elf and other binary symbol extraction pipelines, along with the source side.

The following issues are not reviewed yet, as their parent issue to add functionality has not been completed. I will work on getting symbols from windows/macOS next, and python after that.

* https://github.com/aboutcode-org/scancode.io/issues/1470: https://github.com/aboutcode-org/scancode.io/issues/1431
* https://github.com/aboutcode-org/scancode.io/issues/1471: https://github.com/aboutcode-org/scancode.io/issues/1432
* https://github.com/aboutcode-org/scancode.io/issues/1474: https://github.com/aboutcode-org/scancode.io/issues/1434

Also:

* @keshav-space is working on https://github.com/aboutcode-org/scancode.io/issues/1405 after which we can rerun https://github.com/aboutcode-org/scancode.io/issues/1477
* https://github.com/aboutcode-org/scancode.io/issues/1473 needs to be run with [android inspector](https://github.com/aboutcode-org/android-inspector)

**Comment by AyanSinhaMahapatra** [comment]
A couple of issues which came up during running the scans for all d2d projects which are general issues:

- #1781 
- #1782 
- #1783 
- #1784 
- #1785 
- #1786 
- #1787
- #1788 
- #1789 
- #1790 
- try matching with fully qualified symbols https://github.com/aboutcode-org/source-inspector/issues/28 https://github.com/aboutcode-org/binary-inspector/issues/5
- https://github.com/aboutcode-org/binary-inspector/issues/6
- https://github.com/aboutcode-org/binary-inspector/issues/1
- clean up source symbols (unique + sorted +get rid of numerical/gibberish/weird symbols similarly like we do for binary symbols)
- just include paths and no symbols data in error messages
- enable collecting license detections in d2d pipelines
- show matched/unmatched symbols for binaries and not just for sources (maybe?)

**Comment by pombredanne** [comment]
All sub-issues have been completed.
